image: registry.web.boeing.com/container/images/stack/ubi9minimal-node20:9.4-949-1-2

stages:
  - build      # Stage for building applications
  #- release    # Stage for versioning and tagging
  - deploy     # Stage for deploying applications
  - test       # Stage for PR testing
  - deploy-pages     # Publish the pages out

# Build the Angular component library
build-package:
  stage: build
  only:
    - angular-19
    - develop

  before_script:
    # Set Git user name and email
    - git config --global user.email "dasdesignsystem@boeing.com"
    - git config --global user.name "dasdesignsystem"
    - git config --global --add safe.directory /builds/design/design-system/dls-global-angular
    - git checkout ${CI_COMMIT_REF_NAME}
    - git pull origin ${CI_COMMIT_REF_NAME}
    - echo "Current branch:"
    - git branch -a
  script:
    - |
      if git log -2 --pretty=%B | grep -q "chore(release):"; then
        echo "Skipping pipeline for automated release commit."
        exit 0  # Exit with success to skip the pipeline
      fi
    # Setup .npmrc for npm install
    - echo "registry=https://${JFROG_URL}/${JFROG_REPO}/" > .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:_authToken=${JFROG_AUTHTOKEN}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:username=${JFROG_USER}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:always-auth=true" >> .npmrc
    - echo "@dasdigitalplatform:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "Created the following .npmrc:"; cat .npmrc
    - npm install

    # Check commit message for conventional commit triggers
    - |
      if git log -1 --pretty=%B | grep -Eiq "^(feat|fix|BREAKING CHANGE)"; then
        echo "Version bump needed. Running version-release."
        npm run version-release

        # Capture the new version from package.json
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "New version ${NEW_VERSION}"

        # Ensure subfolder package.json is updated if needed
        # Change directory to the subfolder containing the package.json
        cd projects/design/dls-global-angular/

        # Get the current version from the subfolder's package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")

        # Check if the current version is different from the new version
        if [ "$CURRENT_VERSION" != "$NEW_VERSION" ]; then
          # Update the subfolder's package.json version without creating a Git tag
          echo "Updating subfolder package.json version to ${NEW_VERSION}..."
          npm version ${NEW_VERSION} --no-git-tag-version
        else
          echo "Subfolder package.json is already up to date. No changes needed."
        fi

        # Return to the root directory
        echo "returning to the root directory"
        cd ../../..

        # Push changes only if a new version was created

        # Stage the updated subfolder's package.json for commit
        echo "staging & commiting the updated subfolder's package.json"
        git add projects/design/dls-global-angular/package.json
        # Commit the changes with a message indicating the version sync
        git commit -m "[skip ci] Sync version to ${NEW_VERSION}"


        git remote set-url origin "https://oauth2:${PROJECT_ACCESS_TOKEN}@git.web.boeing.com/design/design-system/dls-global-angular.git"
        # Push the changes to the current branch, including tags
        git push --follow-tags origin HEAD:${CI_COMMIT_REF_NAME}  # Push changes to the current branch
        echo "Pushed changes and tags to the remote repository. Now build the library"

      else
        echo "No version bump needed. Keeping the same version."
      fi

    - echo "Building the library"
    - npm run release

  artifacts:
    paths:
      - dist                            # Store the 'dist' directory as an artifact

# Build the Storybook static site
build-storybook:
  stage: build
  needs:
    - build-package
  only:
    - angular-19
#    - develop
  script:
    - |
      if git log -1 --pretty=%B | grep -q "chore(release):"; then
        echo "Skipping pipeline for automated release commit."
        exit 0  # Exit with success to skip the pipeline
      fi
    # Ensure we have the latest package.json
    - git config --global user.email "dasdesignsystem@boeing.com"
    - git config --global user.name "dasdesignsystem"
    - git config --global --add safe.directory /builds/design/design-system/dls-global-angular
    - git remote set-url origin "https://oauth2:${PROJECT_ACCESS_TOKEN}@git.web.boeing.com/design/design-system/dls-global-angular.git"
    - git pull origin ${CI_COMMIT_REF_NAME}  # Pull the latest package.json

    # Setup .npmrc file
    - echo "registry=https://${JFROG_URL}/${JFROG_REPO}/" > .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:_authToken=${JFROG_AUTHTOKEN}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:username=${JFROG_USER}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:always-auth=true" >> .npmrc
    - echo "@dasdigitalplatform:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "Created the following .npmrc:"; cat .npmrc

    # Clear npm cache and force install latest dependencies
    - npm cache clean --force
    - rm -rf node_modules package-lock.json  # Remove existing dependencies
    - npm install --loglevel verbose             # Install latest dependencies
    - npm run build-storybook                # Build Storybook
  artifacts:
    paths:
      - public                               # Store the 'public' directory as an artifact

# Release stage to handle versioning and tagging
# release:
#   stage: release
#   only:
#     - angular-18
#     - angular-19
#   before_script:
#   # Set Git user name and email
#   - git config --global user.email "dasdesignsystem@boeing.com"
#   - git config --global user.name "dasdesignsystem"
#   - git config --global --add safe.directory /builds/design/design-system/dls-global-angular
#   script:
#    - echo "Running version-release script to bump version and generate changelog.."
#    - export PREVIOUS_VERSION=$(node -p "require('./package.json').version")
#    - echo "Previous version $PREVIOUS_VERSION"
#    - npm install


# Publish Angular component library NPM package
publish-npm:
  stage: deploy
  only:
    - angular-19
    - develop
  script:
    - |
      if git log -1 --pretty=%B | grep -q "chore(release):"; then
        echo "Skipping pipeline for automated release commit."
        exit 0  # Exit with success to skip the pipeline
      fi
    - cd dist/design/dls-global-angular
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    # Extract a few values from package.json
    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - echo "Created the following .npmrc:"; cat .npmrc

    # Validate that the package name is properly scoped to the project's root namespace.
    - |
      if [[ ! $NPM_PACKAGE_NAME =~ ^@$CI_PROJECT_ROOT_NAMESPACE/ ]]; then
        echo "Invalid package scope! Packages must be scoped in the root namespace of the project, e.g. \"@${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}\""
        echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention'
        exit 1
      fi

    # Compare the version in package.json to all published versions.
    - |
      if [[ "$(npm view ${NPM_PACKAGE_NAME} versions)" != *"'${NPM_PACKAGE_VERSION}'"* ]]; then
        if [[ -n "${SIGSTORE_ID_TOKEN}" ]]; then
          npm publish --provenance
        else
          npm publish
        fi
        echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} to GitLab's NPM registry: ${CI_PROJECT_URL}/-/packages"
      else
        echo "Version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} has already been published, so no new version has been published."
      fi



storybook:
  stage: build
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - storybook/
      - public/
  script:
    - |
    - if git log -1 --pretty=%B | grep -q "chore(release):"; then
    - echo "Skipping pipeline for automated release commit."
    - exit 0  # Exit with success to skip the pipeline
    - fi

    # Ensure we have the latest package.json
    - git config --global user.email "dasdesignsystem@boeing.com"
    - git config --global user.name "dasdesignsystem"
    - git config --global --add safe.directory /builds/design/design-system/dls-global-angular
    - git remote set-url origin "https://oauth2:${PROJECT_ACCESS_TOKEN}@git.web.boeing.com/design/design-system/dls-global-angular.git"
    - git pull origin ${CI_COMMIT_REF_NAME}  # Pull the latest package.json

    - echo "registry=https://${JFROG_URL}/${JFROG_REPO}/" > .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:_authToken=${JFROG_AUTHTOKEN}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:username=${JFROG_USER}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:always-auth=true" >> .npmrc
    - echo "@dasdigitalplatform:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "Created the following .npmrc:"; cat .npmrc
    - npm cache clean --force
    - rm -rf node_modules package-lock.json  # Remove existing dependencies
    - npm install --loglevel verbose             # Install latest dependencies
    - |
      if [ "$CI_COMMIT_REF_NAME" != "develop" ]; then
        echo "Build storybook for branch."
        npm run build-storybook -- --output-dir storybook
      else
        echo "Build storybook for develop."
        npm run build-storybook -- --output-dir public
      fi

deploy-storybook:
  stage: deploy
  script:
    - echo "Let's try this"
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://design.pages.boeing.com/design-system/dls-global-angular/$CI_COMMIT_REF_SLUG/storybook/
  #    on_stop: remove STORYBOOK
  #    on_stop: pages-clean-preview
  except:
    - develop
    - release
    - main
    - angular-19

pages:
  stage: deploy-pages
  cache:
    key: 'my-storybook'
    paths:
      - public
  script:
    - echo "mv storybook public/$CI_COMMIT_REF_SLUG"
    - echo "mv storybook $CI_COMMIT_REF_NAME"
    - |
      if [ "$CI_COMMIT_REF_NAME" != "develop" ]; then
        echo "ls public/"
        ls -la "public/" || echo "Directory does not exist yet"
        echo "Build storybook for branch."
        rm -rf "public/$CI_COMMIT_REF_SLUG"
        mkdir -p "public/$CI_COMMIT_REF_SLUG";
        mv storybook "public/$CI_COMMIT_REF_SLUG"
      fi

  artifacts:
    paths:
      - public


# Publish Storybook
#pages:
#  stage: deploy
#  only:
#    - angular-19
#    - develop
#  script:
#    - |
#      if git log -1 --pretty=%B | grep -q "chore(release):"; then
#        echo "Skipping pipeline for automated release commit."
#        exit 0  # Exit with success to skip the pipeline
#      fi
#    - echo "Publishing Storybook..."      # Placeholder for publishing logic
#  artifacts:
#    paths:
#      - public

############################################################################################################

pr-develop:
  stage: test
  only:
    - merge_requests
  script:
    # Log NPM configuration
    - echo "===== NPM Configuration ====="
    - npm config list
    - echo "Registry:$(npm config get registry)"

    # Setup .npmrc for npm install
    - echo "registry=https://${JFROG_URL}/${JFROG_REPO}/" > .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:_password=${JFROG_PASSWORD}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:username=${JFROG_USER}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:always-auth=true" >> .npmrc
    - echo "@dasdigitalplatform:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "Created the following .npmrc:"; cat .npmrc

    # Verify registry access
    - echo "===== Verifying Registry Access ====="
    - curl -I https://${JFROG_URL}/${JFROG_REPO}/ || exit 1

    # Install all dependencies
    - echo "===== Installing Dependencies ====="
    - npm install || exit 1

    # Run build and test scripts
    - echo "===== Running Scripts ====="
    - npm run lib:build || exit 1
    #    - npm run lint:lib || exit 1
    #    - npm run lint:demo || exit 1
    - npm run demo:build || exit 1
    - npm run build-storybook || exit 1

  artifacts:
    paths:
      - coverage/            # Store coverage reports as artifacts
      - lint-results/        # Store lint results as artifacts
