import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/lKCK94JMIgRl52nWS2IB5G/Atmosphere-Foundations-and-Components-Library?node-id=4552-17762&m=dev",
  {
    props: {
      label: figma.string("Label"),
      swapIcon: figma.instance("Swap icon"),
      type: figma.enum("Type", {
        Primary: "primary",
        Accent: "accent",
      }),
      style: figma.enum("Style", {
        Filled: "filled",
        Outlined: "outlined",
        Text: "text",
        Tonal: "tonal",
      }),
      state: figma.enum("State", {
        Enabled: "enabled",
        Hovered: "hovered",
        Pressed: "pressed",
        Disabled: "disabled",
      }),
      showLeadingIcon: figma.boolean("Show leading icon"),
      showTrailingIcon: figma.boolean("Show trailing icon"),
    },
    example: ({ label }) => html`<common-button>${label}</common-button>`,
  },
)
