name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
      - 'angular-*'
      - '*upgrade'
    tags:
      - '2.*'
      - '3.*'
      - '4.*'
  pull_request:
    branches:
      - 'main'
      - 'angular-*'
      - '*upgrade'

jobs:
  lint:
    name: Run linters
    permissions:
      attestations: write
      statuses: write
      id-token: write
      contents: read
      packages: read
    uses: jeppesen-foreflight/dp-jcps-shared-workflows/.github/workflows/lint.yml@spark-fix
    with:
      lint-yaml: true
      node-version: '22.14.0'
      cache-key: node-${{ runner.os }}-20251125-${{ hashFiles('**/package-lock.json') }}
    secrets: inherit
  predict-version-number:
    name: Predict next version number
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      v-version: ${{ steps.version.outputs.v-version }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - name: Get next version
        uses: jeppesen-foreflight/dp-actions-version-increment@v1.2
        id: version
        with:
          scheme: semver
          token: ${{ secrets.GITHUB_TOKEN }}
          increment: patch
          release_branch: main
  codeql-scan:
    name: Run CodeQL scan
    permissions:
      contents: read
      security-events: write
      actions: read
      packages: read
    uses: jeppesen-foreflight/dp-jcps-shared-workflows/.github/workflows/codeql-node-scan.yml@spark-fix
    with:
      node-version: '22.14.0'
      cache-key: node-${{ runner.os }}-20251125-${{ hashFiles('**/package-lock.json') }}
    secrets: inherit
  publish-package:
    name: Publish package
    needs: [predict-version-number]
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    uses: jeppesen-foreflight/dp-jcps-shared-workflows/.github/workflows/build-and-publish-npm-package.yml@spark-fix
    with:
      node-version: '22.14.0'
      package-version: ${{ needs.predict-version-number.outputs.version }}
      project-path: dist/design/dp-dls-global-angular
      cache-key: node-${{ runner.os }}-20251125-${{ hashFiles('**/package-lock.json') }}
    secrets: inherit
  create-release:
    name: Create release
    needs: [predict-version-number, publish-package]
    permissions:
      contents: write
      packages: read
    uses: jeppesen-foreflight/dp-jcps-shared-workflows/.github/workflows/create-release.yml@spark-fix
    with:
      release-version-number: ${{ needs.predict-version-number.outputs.v-version }}